---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:20
    commands:
      - npm ci

  - name: lint
    image: node:20
    commands:
      - npm run lint

  - name: typescript
    image: node:20
    commands:
      - npm run typecheck

trigger:
  event:
    exclude:
      - pull_request
---
kind: signature
hmac: a9741fce539133d2649c0c5918679f3c485f7c130f34000443ab2c48e5bd73db

...
